# Coding sigmoid with numpy 

## Declare W, x, b

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1], [-1], [1]])
x

array([[ 1],
       [-1],
       [ 1]])

In [ ]:
W = np.array([[-1,1,1,], [1,-1,1,], [1,1,-1], [-1,-1,-1]])
W

array([[-1,  1,  1],
       [ 1, -1,  1],
       [ 1,  1, -1],
       [-1, -1, -1]])

In [ ]:
b = np.ones((4,1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

## Forward Propagation

In [ ]:
h_bar = W.dot(x) + b
h_bar

array([[0.],
       [4.],
       [0.],
       [0.]])

In [ ]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

In [ ]:
h = sigmoid(h_bar)
h

array([[0.5       ],
       [0.98201379],
       [0.5       ],
       [0.5       ]])

## Backward Propagation

In [ ]:
v = h * (1 - h)
v

array([[0.25      ],
       [0.01766271],
       [0.25      ],
       [0.25      ]])

In [ ]:
D = np.diag(v[:, 0])
D

array([[0.25      , 0.        , 0.        , 0.        ],
       [0.        , 0.01766271, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.25      ]])

In [ ]:
derivative = D.dot(W)
derivative

array([[-0.25      ,  0.25      ,  0.25      ],
       [ 0.01766271, -0.01766271,  0.01766271],
       [ 0.25      ,  0.25      , -0.25      ],
       [-0.25      , -0.25      , -0.25      ]])

# Grokking Deep Learning

In [2]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
  pred = input.dot(weights)
  return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(round(pred, 2))

0.98


In [6]:
import numpy as np 

a = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7]])

b = np.zeros((2, 4))

c = np.random.rand(2,5)

print(a.shape)
print(a)
print(b) 
print(c)

(2, 4)
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.27757813 0.99045142 0.90459456 0.34969381 0.92218362]
 [0.84608701 0.47134264 0.09906108 0.01254366 0.08701665]]
