# Coding sigmoid with numpy 

## Declare W, x, b

In [2]:
import numpy as np

In [3]:
x = np.array([[1], [-1], [1]])
x

array([[ 1],
       [-1],
       [ 1]])

In [4]:
W = np.array([[-1,1,1,], [1,-1,1,], [1,1,-1], [-1,-1,-1]])
W

array([[-1,  1,  1],
       [ 1, -1,  1],
       [ 1,  1, -1],
       [-1, -1, -1]])

In [7]:
b = np.ones((4,1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

## Forward Propagation

In [8]:
h_bar = W.dot(x) + b
h_bar

array([[0.],
       [4.],
       [0.],
       [0.]])

In [9]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

In [10]:
h = sigmoid(h_bar)
h

array([[0.5       ],
       [0.98201379],
       [0.5       ],
       [0.5       ]])

## Backward Propagation

In [11]:
v = h * (1 - h)
v

array([[0.25      ],
       [0.01766271],
       [0.25      ],
       [0.25      ]])

In [12]:
D = np.diag(v[:, 0])
D

array([[0.25      , 0.        , 0.        , 0.        ],
       [0.        , 0.01766271, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.25      ]])

In [13]:
derivative = D.dot(W)
derivative

array([[-0.25      ,  0.25      ,  0.25      ],
       [ 0.01766271, -0.01766271,  0.01766271],
       [ 0.25      ,  0.25      , -0.25      ],
       [-0.25      , -0.25      , -0.25      ]])